### ISSUE TITLE
undefined symbol: _ZN5model6Engine10ParseSpecsEN6config18CompoundConfigNodeE

### ISSUE THREAD

**Issue by chenshih1** [maestro-project/gamma-timeloop#1]
Hello, I've tried to install gamma with timeloop, and the installation seems to be successful. But when I run the example scripts by `bash run_gamma_timeloop.sh` and `bash run_gamma_timeloop_multiObjective.sh`, there's an ImportError caused by undefined symbol.

The complete log is as follows.

`root@83fe54e1ae36:~/gamma-timeloop# bash run_gamma_timeloop.sh 
Traceback (most recent call last):
  File "/root/gamma-timeloop/src/main.py", line 1, in <module>
    from gamma_timeloop_env import GammaTimeloopEnv
  File "/root/gamma-timeloop/src/gamma_timeloop_env.py", line 7, in <module>
    from timeloop_env import TimeloopEnv
  File "/root/gamma-timeloop/src/timeloop_env.py", line 9, in <module>
    from pytimeloop.app import Model
  File "/root/pytimeloop/pytimeloop/__init__.py", line 1, in <module>
    from bindings import *
ImportError: /root/pytimeloop/bindings.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN5model6Engine10ParseSpecsEN6config18CompoundConfigNodeE
`

**Comment by EMJzero** [comment]
Hi, I have the same issue, and it is related to **pytimeloop**, take a look here:

https://github.com/Accelergy-Project/timeloop-python/issues/29

For now I managed to circumvent it by using the Docker container provided with Timeloop (see [here](https://github.com/Accelergy-Project/accelergy-timeloop-infrastructure/tree/master)), however you need to manually build barvinok and install it inside the container, but that's easy by following the same commands as the Makefile for Timeloop's infrastructure: https://github.com/Accelergy-Project/accelergy-timeloop-infrastructure/blob/1f6bf7cf0071d43e87d5351be3ff960f03af523d/Makefile#L159

I know it's been 4 months, but maybe I could still help.
Let's trust the pytimeloop guys to fix this issue sooner or later.
